/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.31
 * Generated at: 2018-07-13 00:18:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1531354288000L));
    _jspx_dependants.put("jar:file:/C:/JAGOGAgit/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AdminForm/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 
	request.setCharacterEncoding("UTF-8"); 
	String cp = request.getContextPath();

      out.write('\r');
      out.write('\n');

	String memId = null;
	/* if (session.getAttribute("id") != null) 
		memId = (String)session.getAttribute("id"); */

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0\">\r\n");
      out.write("\t<!-- VENDOR CSS -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/vendor/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/vendor/font-awesome/css/font-awesome.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/vendor/linearicons/style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/vendor/chartist/css/chartist-custom.css\">\r\n");
      out.write("\t<!-- MAIN CSS -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/main.css\">\r\n");
      out.write("\t<!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/demo.css\">\r\n");
      out.write("\t<!-- GOOGLE FONTS -->\r\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700\" rel=\"stylesheet\">\r\n");
      out.write("\t<!-- ICONS -->\r\n");
      out.write("\t<link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"assets/img/apple-icon.png\">\r\n");
      out.write("\t<link rel=\"icon\" type=\"image/png\" sizes=\"96x96\" href=\"assets/img/favicon.png\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- WRAPPER -->\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t\t<!-- NAVBAR -->\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t<!-- <nav class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("\t\t\t<div class=\"brand\">\r\n");
      out.write("\t\t\t\t<a href=\"index.html\"><img src=\"assets/img/logo-dark.png\" alt=\"Klorofil Logo\" class=\"img-responsive logo\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t<div class=\"navbar-btn\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn-toggle-fullwidth\"><i class=\"lnr lnr-arrow-left-circle\"></i></button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"navbar-menu\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle icon-menu\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"lnr lnr-alarm\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"badge bg-danger\">5</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu notifications\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"notification-item\"><span class=\"dot bg-warning\"></span>System space is almost full</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"notification-item\"><span class=\"dot bg-danger\"></span>You have 9 unfinished tasks</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"notification-item\"><span class=\"dot bg-success\"></span>Monthly report is available</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"notification-item\"><span class=\"dot bg-warning\"></span>Weekly meeting in 1 hour</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"notification-item\"><span class=\"dot bg-success\"></span>Your request has been approved</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"more\">See all notifications</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><i class=\"lnr lnr-question-circle\"></i> <span>Help</span> <i class=\"icon-submenu lnr lnr-chevron-down\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Basic Use</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Working With Data</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Security</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Troubleshooting</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><img src=\"assets/img/user.png\" class=\"img-circle\" alt=\"Avatar\"> <span>Samuel</span> <i class=\"icon-submenu lnr lnr-chevron-down\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"lnr lnr-user\"></i> <span>My Profile</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"lnr lnr-envelope\"></i> <span>Message</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"lnr lnr-cog\"></i> <span>Settings</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"lnr lnr-exit\"></i> <span>Logout</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"update-pro\" href=\"https://www.themeineed.com/downloads/klorofil-pro-bootstrap-admin-dashboard-template/?utm_source=klorofil&utm_medium=template&utm_campaign=KlorofilPro\" title=\"Upgrade to Pro\" target=\"_blank\"><i class=\"fa fa-rocket\"></i> <span>UPGRADE TO PRO</span></a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav> -->\r\n");
      out.write("\t\t<!-- END NAVBAR -->\r\n");
      out.write("\t\t<!-- LEFT SIDEBAR -->\r\n");
      out.write("\t\t<div id=\"sidebar-nav\" class=\"sidebar\">\r\n");
      out.write("\t\t\t<div class=\"sidebar-scroll\">\r\n");
      out.write("\t\t\t\t<nav>\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"index.html\" class=\"active\"><i class=\"lnr lnr-home\"></i> <span>Dashboard</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"elements.html\" class=\"\"><i class=\"lnr lnr-code\"></i> <span>Elements</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"charts.html\" class=\"\"><i class=\"lnr lnr-chart-bars\"></i> <span>Charts</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"panels.html\" class=\"\"><i class=\"lnr lnr-cog\"></i> <span>Panels</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"notifications.html\" class=\"\"><i class=\"lnr lnr-alarm\"></i> <span>Notifications</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#subPages\" data-toggle=\"collapse\" class=\"collapsed\"><i class=\"lnr lnr-file-empty\"></i> <span>Pages</span> <i class=\"icon-submenu lnr lnr-chevron-left\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"subPages\" class=\"collapse \">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"nav\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"page-profile.html\" class=\"\">Profile</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"page-login.html\" class=\"\">Login</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"page-lockscreen.html\" class=\"\">Lockscreen</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"tables.html\" class=\"\"><i class=\"lnr lnr-dice\"></i> <span>Tables</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"typography.html\" class=\"\"><i class=\"lnr lnr-text-format\"></i> <span>Typography</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"icons.html\" class=\"\"><i class=\"lnr lnr-linearicons\"></i> <span>Icons</span></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- END LEFT SIDEBAR -->\r\n");
      out.write("\t\t<!-- MAIN -->\r\n");
      out.write("\t\t<div class=\"main\">\r\n");
      out.write("\t\t\t<!-- MAIN CONTENT -->\r\n");
      out.write("\t\t\t<div class=\"main-content\">\r\n");
      out.write("\t\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t\t<!-- OVERVIEW -->\r\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-headline\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"panel-title\">Weekly Overview</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"panel-subtitle\">Period: Oct 14, 2016 - Oct 21, 2016</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"metric\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"icon\"><i class=\"fa fa-download\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"number\">1,252</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"title\">Downloads</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"metric\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"icon\"><i class=\"fa fa-shopping-bag\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"number\">203</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"title\">Sales</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"metric\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"icon\"><i class=\"fa fa-eye\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"number\">274,678</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"title\">Visits</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"metric\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"icon\"><i class=\"fa fa-bar-chart\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"number\">35%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"title\">Conversions</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"headline-chart\" class=\"ct-chart\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"weekly-summary text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"number\">2,315</span> <span class=\"percentage\"><i class=\"fa fa-caret-up text-success\"></i> 12%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"info-label\">Total Sales</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"weekly-summary text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"number\">$5,758</span> <span class=\"percentage\"><i class=\"fa fa-caret-up text-success\"></i> 23%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"info-label\">Monthly Income</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"weekly-summary text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"number\">$65,938</span> <span class=\"percentage\"><i class=\"fa fa-caret-down text-danger\"></i> 8%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"info-label\">Total Income</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- END OVERVIEW -->\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- RECENT PURCHASES -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"panel-title\">Recent Purchases</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn-toggle-collapse\"><i class=\"lnr lnr-chevron-up\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn-remove\"><i class=\"lnr lnr-cross\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-body no-padding\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table class=\"table table-striped\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>Order No.</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>Amount</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>Date &amp; Time</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>Status</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><a href=\"#\">763648</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>Steve</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>$122</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>Oct 21, 2016</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><span class=\"label label-success\">COMPLETED</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><a href=\"#\">763649</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>Amber</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>$62</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>Oct 21, 2016</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><span class=\"label label-warning\">PENDING</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><a href=\"#\">763650</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>Michael</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>$34</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>Oct 18, 2016</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><span class=\"label label-danger\">FAILED</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><a href=\"#\">763651</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>Roger</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>$186</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>Oct 17, 2016</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><span class=\"label label-success\">SUCCESS</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><a href=\"#\">763652</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>Smith</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>$362</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>Oct 16, 2016</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><span class=\"label label-success\">SUCCESS</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\"><span class=\"panel-note\"><i class=\"fa fa-clock-o\"></i> Last 24 hours</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6 text-right\"><a href=\"#\" class=\"btn btn-primary\">View All Purchases</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- END RECENT PURCHASES -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- MULTI CHARTS -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"panel-title\">Projection vs. Realization</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn-toggle-collapse\"><i class=\"lnr lnr-chevron-up\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn-remove\"><i class=\"lnr lnr-cross\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"visits-trends-chart\" class=\"ct-chart\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- END MULTI CHARTS -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-7\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- TODO LIST -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"panel-title\">To-Do List</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn-toggle-collapse\"><i class=\"lnr lnr-chevron-up\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn-remove\"><i class=\"lnr lnr-cross\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled todo-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-inline fancy-checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\"><span></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"title\">Restart Server</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"short-description\">Dynamically integrate client-centric technologies without cooperative resources.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"date\">Oct 9, 2016</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><i class=\"icon-software icon-software-pencil\"></i></a> <a href=\"#\"><i class=\"icon-arrows icon-arrows-circle-remove\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-inline fancy-checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\"><span></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"title\">Retest Upload Scenario</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"short-description\">Compellingly implement clicks-and-mortar relationships without highly efficient metrics.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"date\">Oct 23, 2016</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><i class=\"icon-software icon-software-pencil\"></i></a> <a href=\"#\"><i class=\"icon-arrows icon-arrows-circle-remove\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-inline fancy-checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\"><span></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<strong>Functional Spec Meeting</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"short-description\">Monotonectally formulate client-focused core competencies after parallel web-readiness.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"date\">Oct 11, 2016</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><i class=\"icon-software icon-software-pencil\"></i></a> <a href=\"#\"><i class=\"icon-arrows icon-arrows-circle-remove\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- END TODO LIST -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-5\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- TIMELINE -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel panel-scrolling\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"panel-title\">Recent User Activity</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn-toggle-collapse\"><i class=\"lnr lnr-chevron-up\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn-remove\"><i class=\"lnr lnr-cross\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled activity-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"assets/img/user1.png\" alt=\"Avatar\" class=\"img-circle pull-left avatar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p><a href=\"#\">Michael</a> has achieved 80% of his completed tasks <span class=\"timestamp\">20 minutes ago</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"assets/img/user2.png\" alt=\"Avatar\" class=\"img-circle pull-left avatar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p><a href=\"#\">Daniel</a> has been added as a team member to project <a href=\"#\">System Update</a> <span class=\"timestamp\">Yesterday</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"assets/img/user3.png\" alt=\"Avatar\" class=\"img-circle pull-left avatar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p><a href=\"#\">Martha</a> created a new heatmap view <a href=\"#\">Landing Page</a> <span class=\"timestamp\">2 days ago</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"assets/img/user4.png\" alt=\"Avatar\" class=\"img-circle pull-left avatar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p><a href=\"#\">Jane</a> has completed all of the tasks <span class=\"timestamp\">2 days ago</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"assets/img/user5.png\" alt=\"Avatar\" class=\"img-circle pull-left avatar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p><a href=\"#\">Jason</a> started a discussion about <a href=\"#\">Weekly Meeting</a> <span class=\"timestamp\">3 days ago</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary btn-bottom center-block\">Load More</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- END TIMELINE -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- TASKS -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"panel-title\">My Tasks</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn-toggle-collapse\"><i class=\"lnr lnr-chevron-up\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn-remove\"><i class=\"lnr lnr-cross\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled task-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Updating Users Settings <span class=\"label-percent\">23%</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-xs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-bar progress-bar-danger\" role=\"progressbar\" aria-valuenow=\"23\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width:23%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"sr-only\">23% Complete</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Load &amp; Stress Test <span class=\"label-percent\">80%</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-xs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-bar progress-bar-success\" role=\"progressbar\" aria-valuenow=\"80\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 80%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"sr-only\">80% Complete</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Data Duplication Check <span class=\"label-percent\">100%</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-xs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-bar progress-bar-success\" role=\"progressbar\" aria-valuenow=\"100\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"sr-only\">Success</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Server Check <span class=\"label-percent\">45%</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-xs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-bar progress-bar-warning\" role=\"progressbar\" aria-valuenow=\"45\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 45%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"sr-only\">45% Complete</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Mobile App Development <span class=\"label-percent\">10%</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress progress-xs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-bar progress-bar-danger\" role=\"progressbar\" aria-valuenow=\"10\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"sr-only\">10% Complete</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- END TASKS -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- VISIT CHART -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"panel-title\">Website Visits</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn-toggle-collapse\"><i class=\"lnr lnr-chevron-up\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn-remove\"><i class=\"lnr lnr-cross\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"visits-chart\" class=\"ct-chart\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- END VISIT CHART -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- REALTIME CHART -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"panel-title\">System Load</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn-toggle-collapse\"><i class=\"lnr lnr-chevron-up\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn-remove\"><i class=\"lnr lnr-cross\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"system-load\" class=\"easy-pie-chart\" data-percent=\"70\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"percent\">70</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>CPU Load</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled list-justify\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>High: <span>95%</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>Average: <span>87%</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>Low: <span>20%</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>Threads: <span>996</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>Processes: <span>259</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- END REALTIME CHART -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- END MAIN CONTENT -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- END MAIN -->\r\n");
      out.write("\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t<p class=\"copyright\">Shared by <i class=\"fa fa-love\"></i><a href=\"https://bootstrapthemes.co\">BootstrapThemes</a>\r\n");
      out.write("</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END WRAPPER -->\r\n");
      out.write("\t<!-- Javascript -->\r\n");
      out.write("\t<script src=\"assets/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/vendor/chartist/js/chartist.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/scripts/klorofil-common.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar data, options;\r\n");
      out.write("\r\n");
      out.write("\t\t// headline charts\r\n");
      out.write("\t\tdata = {\r\n");
      out.write("\t\t\tlabels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],\r\n");
      out.write("\t\t\tseries: [\r\n");
      out.write("\t\t\t\t[23, 29, 24, 40, 25, 24, 35],\r\n");
      out.write("\t\t\t\t[14, 25, 18, 34, 29, 38, 44],\r\n");
      out.write("\t\t\t]\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\toptions = {\r\n");
      out.write("\t\t\theight: 300,\r\n");
      out.write("\t\t\tshowArea: true,\r\n");
      out.write("\t\t\tshowLine: false,\r\n");
      out.write("\t\t\tshowPoint: false,\r\n");
      out.write("\t\t\tfullWidth: true,\r\n");
      out.write("\t\t\taxisX: {\r\n");
      out.write("\t\t\t\tshowGrid: false\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tlineSmooth: false,\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\tnew Chartist.Line('#headline-chart', data, options);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t// visits trend charts\r\n");
      out.write("\t\tdata = {\r\n");
      out.write("\t\t\tlabels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],\r\n");
      out.write("\t\t\tseries: [{\r\n");
      out.write("\t\t\t\tname: 'series-real',\r\n");
      out.write("\t\t\t\tdata: [200, 380, 350, 320, 410, 450, 570, 400, 555, 620, 750, 900],\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tname: 'series-projection',\r\n");
      out.write("\t\t\t\tdata: [240, 350, 360, 380, 400, 450, 480, 523, 555, 600, 700, 800],\r\n");
      out.write("\t\t\t}]\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\toptions = {\r\n");
      out.write("\t\t\tfullWidth: true,\r\n");
      out.write("\t\t\tlineSmooth: false,\r\n");
      out.write("\t\t\theight: \"270px\",\r\n");
      out.write("\t\t\tlow: 0,\r\n");
      out.write("\t\t\thigh: 'auto',\r\n");
      out.write("\t\t\tseries: {\r\n");
      out.write("\t\t\t\t'series-projection': {\r\n");
      out.write("\t\t\t\t\tshowArea: true,\r\n");
      out.write("\t\t\t\t\tshowPoint: false,\r\n");
      out.write("\t\t\t\t\tshowLine: false\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\taxisX: {\r\n");
      out.write("\t\t\t\tshowGrid: false,\r\n");
      out.write("\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\taxisY: {\r\n");
      out.write("\t\t\t\tshowGrid: false,\r\n");
      out.write("\t\t\t\tonlyInteger: true,\r\n");
      out.write("\t\t\t\toffset: 0,\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tchartPadding: {\r\n");
      out.write("\t\t\t\tleft: 20,\r\n");
      out.write("\t\t\t\tright: 20\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\tnew Chartist.Line('#visits-trends-chart', data, options);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t// visits chart\r\n");
      out.write("\t\tdata = {\r\n");
      out.write("\t\t\tlabels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],\r\n");
      out.write("\t\t\tseries: [\r\n");
      out.write("\t\t\t\t[6384, 6342, 5437, 2764, 3958, 5068, 7654]\r\n");
      out.write("\t\t\t]\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\toptions = {\r\n");
      out.write("\t\t\theight: 300,\r\n");
      out.write("\t\t\taxisX: {\r\n");
      out.write("\t\t\t\tshowGrid: false\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\tnew Chartist.Bar('#visits-chart', data, options);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t// real-time pie chart\r\n");
      out.write("\t\tvar sysLoad = $('#system-load').easyPieChart({\r\n");
      out.write("\t\t\tsize: 130,\r\n");
      out.write("\t\t\tbarColor: function(percent) {\r\n");
      out.write("\t\t\t\treturn \"rgb(\" + Math.round(200 * percent / 100) + \", \" + Math.round(200 * (1.1 - percent / 100)) + \", 0)\";\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\ttrackColor: 'rgba(245, 245, 245, 0.8)',\r\n");
      out.write("\t\t\tscaleColor: false,\r\n");
      out.write("\t\t\tlineWidth: 5,\r\n");
      out.write("\t\t\tlineCap: \"square\",\r\n");
      out.write("\t\t\tanimate: 800\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar updateInterval = 3000; // in milliseconds\r\n");
      out.write("\r\n");
      out.write("\t\tsetInterval(function() {\r\n");
      out.write("\t\t\tvar randomVal;\r\n");
      out.write("\t\t\trandomVal = getRandomInt(0, 100);\r\n");
      out.write("\r\n");
      out.write("\t\t\tsysLoad.data('easyPieChart').update(randomVal);\r\n");
      out.write("\t\t\tsysLoad.find('.percent').text(randomVal);\r\n");
      out.write("\t\t}, updateInterval);\r\n");
      out.write("\r\n");
      out.write("\t\tfunction getRandomInt(min, max) {\r\n");
      out.write("\t\t\treturn Math.floor(Math.random() * (max - min + 1)) + min;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /index.jsp(38,2) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("AdminLoginMainbar.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }
}
